# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a13cf877db2a9dbc1119b90eb287a7cf"
name = "Profit Guard"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
