// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/webhooks/app_subscriptions/update": {
    params: {};
  };
  "/webhooks/customers/data_request": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/webhooks/customers/redact": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/webhooks/shop/redact": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/healthz": {
    params: {};
  };
  "/privacy": {
    params: {};
  };
  "/support": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/refund": {
    params: {};
  };
  "/terms": {
    params: {};
  };
  "/beta": {
    params: {};
  };
  "/app": {
    params: {};
  };
  "/app/onboarding": {
    params: {};
  };
  "/app/settings": {
    params: {};
  };
  "/app/pricing": {
    params: {};
  };
  "/app/alerts": {
    params: {};
  };
  "/app/export": {
    params: {};
  };
  "/app/import": {
    params: {};
  };
  "/app/csv": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/webhooks/app_subscriptions/update" | "/webhooks/customers/data_request" | "/webhooks/app/scopes_update" | "/webhooks/customers/redact" | "/webhooks/app/uninstalled" | "/webhooks/shop/redact" | "/auth/login" | "/healthz" | "/privacy" | "/support" | "/auth/*" | "/refund" | "/terms" | "/beta" | "/app" | "/app/onboarding" | "/app/settings" | "/app/pricing" | "/app/alerts" | "/app/export" | "/app/import" | "/app/csv";
  };
  "routes/webhooks.app_subscriptions.update.tsx": {
    id: "routes/webhooks.app_subscriptions.update";
    page: "/webhooks/app_subscriptions/update";
  };
  "routes/webhooks.customers.data_request.tsx": {
    id: "routes/webhooks.customers.data_request";
    page: "/webhooks/customers/data_request";
  };
  "routes/webhooks.app.scopes_update.tsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/webhooks.customers.redact.tsx": {
    id: "routes/webhooks.customers.redact";
    page: "/webhooks/customers/redact";
  };
  "routes/webhooks.app.uninstalled.tsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/webhooks.shop.redact.tsx": {
    id: "routes/webhooks.shop.redact";
    page: "/webhooks/shop/redact";
  };
  "routes/auth.login/route.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/healthz.tsx": {
    id: "routes/healthz";
    page: "/healthz";
  };
  "routes/privacy.tsx": {
    id: "routes/privacy";
    page: "/privacy";
  };
  "routes/support.tsx": {
    id: "routes/support";
    page: "/support";
  };
  "routes/_index/route.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/auth.$.tsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/refund.tsx": {
    id: "routes/refund";
    page: "/refund";
  };
  "routes/terms.tsx": {
    id: "routes/terms";
    page: "/terms";
  };
  "routes/beta.tsx": {
    id: "routes/beta";
    page: "/beta";
  };
  "routes/app.tsx": {
    id: "routes/app";
    page: "/app" | "/app/onboarding" | "/app/settings" | "/app/pricing" | "/app/alerts" | "/app/export" | "/app/import" | "/app/csv";
  };
  "routes/app.onboarding.tsx": {
    id: "routes/app.onboarding";
    page: "/app/onboarding";
  };
  "routes/app.settings.tsx": {
    id: "routes/app.settings";
    page: "/app/settings";
  };
  "routes/app.pricing.tsx": {
    id: "routes/app.pricing";
    page: "/app/pricing";
  };
  "routes/app._index.tsx": {
    id: "routes/app._index";
    page: "/app";
  };
  "routes/app.alerts.tsx": {
    id: "routes/app.alerts";
    page: "/app/alerts";
  };
  "routes/app.export.tsx": {
    id: "routes/app.export";
    page: "/app/export";
  };
  "routes/app.import.tsx": {
    id: "routes/app.import";
    page: "/app/import";
  };
  "routes/app.csv.tsx": {
    id: "routes/app.csv";
    page: "/app/csv";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/webhooks.app_subscriptions.update": typeof import("./app/routes/webhooks.app_subscriptions.update.tsx");
  "routes/webhooks.customers.data_request": typeof import("./app/routes/webhooks.customers.data_request.tsx");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.tsx");
  "routes/webhooks.customers.redact": typeof import("./app/routes/webhooks.customers.redact.tsx");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.tsx");
  "routes/webhooks.shop.redact": typeof import("./app/routes/webhooks.shop.redact.tsx");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.tsx");
  "routes/healthz": typeof import("./app/routes/healthz.tsx");
  "routes/privacy": typeof import("./app/routes/privacy.tsx");
  "routes/support": typeof import("./app/routes/support.tsx");
  "routes/_index": typeof import("./app/routes/_index/route.tsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.tsx");
  "routes/refund": typeof import("./app/routes/refund.tsx");
  "routes/terms": typeof import("./app/routes/terms.tsx");
  "routes/beta": typeof import("./app/routes/beta.tsx");
  "routes/app": typeof import("./app/routes/app.tsx");
  "routes/app.onboarding": typeof import("./app/routes/app.onboarding.tsx");
  "routes/app.settings": typeof import("./app/routes/app.settings.tsx");
  "routes/app.pricing": typeof import("./app/routes/app.pricing.tsx");
  "routes/app._index": typeof import("./app/routes/app._index.tsx");
  "routes/app.alerts": typeof import("./app/routes/app.alerts.tsx");
  "routes/app.export": typeof import("./app/routes/app.export.tsx");
  "routes/app.import": typeof import("./app/routes/app.import.tsx");
  "routes/app.csv": typeof import("./app/routes/app.csv.tsx");
};