// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/webhooks/app_subscriptions/update": {
    params: {};
  };
  "/webhooks/customers/data_request": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/webhooks/customers/redact": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/webhooks/shop/redact": {
    params: {};
  };
  "/webhooks/compliance": {
    params: {};
  };
  "/internal/metrics": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/resources": {
    params: {};
  };
  "/resources/find-low-margin-products-shopify": {
    params: {};
  };
  "/resources/bulk-price-update-margin-check": {
    params: {};
  };
  "/resources/supplier-cost-csv-margin-scan": {
    params: {};
  };
  "/resources/stocky-cost-margin-workflow": {
    params: {};
  };
  "/resources/shopify-unit-cost-missing": {
    params: {};
  };
  "/healthz": {
    params: {};
  };
  "/privacy": {
    params: {};
  };
  "/support": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/refund": {
    params: {};
  };
  "/terms": {
    params: {};
  };
  "/beta": {
    params: {};
  };
  "/app": {
    params: {};
  };
  "/app/onboarding": {
    params: {};
  };
  "/app/settings": {
    params: {};
  };
  "/app/metrics": {
    params: {};
  };
  "/app/pricing": {
    params: {};
  };
  "/app/what-if": {
    params: {};
  };
  "/app/alerts": {
    params: {};
  };
  "/app/export": {
    params: {};
  };
  "/app/import": {
    params: {};
  };
  "/app/import/template": {
    params: {};
  };
  "/app/csv": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/webhooks/app_subscriptions/update" | "/webhooks/customers/data_request" | "/webhooks/app/scopes_update" | "/webhooks/customers/redact" | "/webhooks/app/uninstalled" | "/webhooks/shop/redact" | "/webhooks/compliance" | "/internal/metrics" | "/auth/login" | "/resources" | "/resources/find-low-margin-products-shopify" | "/resources/bulk-price-update-margin-check" | "/resources/supplier-cost-csv-margin-scan" | "/resources/stocky-cost-margin-workflow" | "/resources/shopify-unit-cost-missing" | "/healthz" | "/privacy" | "/support" | "/auth/*" | "/refund" | "/terms" | "/beta" | "/app" | "/app/onboarding" | "/app/settings" | "/app/metrics" | "/app/pricing" | "/app/what-if" | "/app/alerts" | "/app/export" | "/app/import" | "/app/import/template" | "/app/csv";
  };
  "routes/webhooks.app_subscriptions.update.tsx": {
    id: "routes/webhooks.app_subscriptions.update";
    page: "/webhooks/app_subscriptions/update";
  };
  "routes/webhooks.customers.data_request.tsx": {
    id: "routes/webhooks.customers.data_request";
    page: "/webhooks/customers/data_request";
  };
  "routes/webhooks.app.scopes_update.tsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/webhooks.customers.redact.tsx": {
    id: "routes/webhooks.customers.redact";
    page: "/webhooks/customers/redact";
  };
  "routes/webhooks.app.uninstalled.tsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/webhooks.shop.redact.tsx": {
    id: "routes/webhooks.shop.redact";
    page: "/webhooks/shop/redact";
  };
  "routes/webhooks.compliance.tsx": {
    id: "routes/webhooks.compliance";
    page: "/webhooks/compliance";
  };
  "routes/internal.metrics.tsx": {
    id: "routes/internal.metrics";
    page: "/internal/metrics";
  };
  "routes/auth.login/route.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/resources.tsx": {
    id: "routes/resources";
    page: "/resources" | "/resources/find-low-margin-products-shopify" | "/resources/bulk-price-update-margin-check" | "/resources/supplier-cost-csv-margin-scan" | "/resources/stocky-cost-margin-workflow" | "/resources/shopify-unit-cost-missing";
  };
  "routes/resources.find-low-margin-products-shopify.tsx": {
    id: "routes/resources.find-low-margin-products-shopify";
    page: "/resources/find-low-margin-products-shopify";
  };
  "routes/resources.bulk-price-update-margin-check.tsx": {
    id: "routes/resources.bulk-price-update-margin-check";
    page: "/resources/bulk-price-update-margin-check";
  };
  "routes/resources.supplier-cost-csv-margin-scan.tsx": {
    id: "routes/resources.supplier-cost-csv-margin-scan";
    page: "/resources/supplier-cost-csv-margin-scan";
  };
  "routes/resources.stocky-cost-margin-workflow.tsx": {
    id: "routes/resources.stocky-cost-margin-workflow";
    page: "/resources/stocky-cost-margin-workflow";
  };
  "routes/resources.shopify-unit-cost-missing.tsx": {
    id: "routes/resources.shopify-unit-cost-missing";
    page: "/resources/shopify-unit-cost-missing";
  };
  "routes/healthz.tsx": {
    id: "routes/healthz";
    page: "/healthz";
  };
  "routes/privacy.tsx": {
    id: "routes/privacy";
    page: "/privacy";
  };
  "routes/support.tsx": {
    id: "routes/support";
    page: "/support";
  };
  "routes/_index/route.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/auth.$.tsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/refund.tsx": {
    id: "routes/refund";
    page: "/refund";
  };
  "routes/terms.tsx": {
    id: "routes/terms";
    page: "/terms";
  };
  "routes/beta.tsx": {
    id: "routes/beta";
    page: "/beta";
  };
  "routes/app.tsx": {
    id: "routes/app";
    page: "/app" | "/app/onboarding" | "/app/settings" | "/app/metrics" | "/app/pricing" | "/app/what-if" | "/app/alerts" | "/app/export" | "/app/import" | "/app/import/template" | "/app/csv";
  };
  "routes/app.onboarding.tsx": {
    id: "routes/app.onboarding";
    page: "/app/onboarding";
  };
  "routes/app.settings.tsx": {
    id: "routes/app.settings";
    page: "/app/settings";
  };
  "routes/app.metrics.tsx": {
    id: "routes/app.metrics";
    page: "/app/metrics";
  };
  "routes/app.pricing.tsx": {
    id: "routes/app.pricing";
    page: "/app/pricing";
  };
  "routes/app.what-if.tsx": {
    id: "routes/app.what-if";
    page: "/app/what-if";
  };
  "routes/app._index.tsx": {
    id: "routes/app._index";
    page: "/app";
  };
  "routes/app.alerts.tsx": {
    id: "routes/app.alerts";
    page: "/app/alerts";
  };
  "routes/app.export.tsx": {
    id: "routes/app.export";
    page: "/app/export";
  };
  "routes/app.import.tsx": {
    id: "routes/app.import";
    page: "/app/import" | "/app/import/template";
  };
  "routes/app.import.template.tsx": {
    id: "routes/app.import.template";
    page: "/app/import/template";
  };
  "routes/app.csv.tsx": {
    id: "routes/app.csv";
    page: "/app/csv";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/webhooks.app_subscriptions.update": typeof import("./app/routes/webhooks.app_subscriptions.update.tsx");
  "routes/webhooks.customers.data_request": typeof import("./app/routes/webhooks.customers.data_request.tsx");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.tsx");
  "routes/webhooks.customers.redact": typeof import("./app/routes/webhooks.customers.redact.tsx");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.tsx");
  "routes/webhooks.shop.redact": typeof import("./app/routes/webhooks.shop.redact.tsx");
  "routes/webhooks.compliance": typeof import("./app/routes/webhooks.compliance.tsx");
  "routes/internal.metrics": typeof import("./app/routes/internal.metrics.tsx");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.tsx");
  "routes/resources": typeof import("./app/routes/resources.tsx");
  "routes/resources.find-low-margin-products-shopify": typeof import("./app/routes/resources.find-low-margin-products-shopify.tsx");
  "routes/resources.bulk-price-update-margin-check": typeof import("./app/routes/resources.bulk-price-update-margin-check.tsx");
  "routes/resources.supplier-cost-csv-margin-scan": typeof import("./app/routes/resources.supplier-cost-csv-margin-scan.tsx");
  "routes/resources.stocky-cost-margin-workflow": typeof import("./app/routes/resources.stocky-cost-margin-workflow.tsx");
  "routes/resources.shopify-unit-cost-missing": typeof import("./app/routes/resources.shopify-unit-cost-missing.tsx");
  "routes/healthz": typeof import("./app/routes/healthz.tsx");
  "routes/privacy": typeof import("./app/routes/privacy.tsx");
  "routes/support": typeof import("./app/routes/support.tsx");
  "routes/_index": typeof import("./app/routes/_index/route.tsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.tsx");
  "routes/refund": typeof import("./app/routes/refund.tsx");
  "routes/terms": typeof import("./app/routes/terms.tsx");
  "routes/beta": typeof import("./app/routes/beta.tsx");
  "routes/app": typeof import("./app/routes/app.tsx");
  "routes/app.onboarding": typeof import("./app/routes/app.onboarding.tsx");
  "routes/app.settings": typeof import("./app/routes/app.settings.tsx");
  "routes/app.metrics": typeof import("./app/routes/app.metrics.tsx");
  "routes/app.pricing": typeof import("./app/routes/app.pricing.tsx");
  "routes/app.what-if": typeof import("./app/routes/app.what-if.tsx");
  "routes/app._index": typeof import("./app/routes/app._index.tsx");
  "routes/app.alerts": typeof import("./app/routes/app.alerts.tsx");
  "routes/app.export": typeof import("./app/routes/app.export.tsx");
  "routes/app.import": typeof import("./app/routes/app.import.tsx");
  "routes/app.import.template": typeof import("./app/routes/app.import.template.tsx");
  "routes/app.csv": typeof import("./app/routes/app.csv.tsx");
};